version: '3.3'

services:
  alphabet-compose:
    build:
      context: .
      target: build-stage
    container_name: alphabet-compose
    entrypoint: ["/www/entrypoint-dev.sh"]
    volumes:
      - .:/www:delegated
    ports:
      - 5173:5173
