# build
ARG DOCKER_REG=nexus.supercode.ru:8444

FROM node:20-alpine as build-stage

ARG CYPRESS_INSTALL_BINARY

ENV VUE_APP_PUBLIC_PATH=$VUE_APP_PUBLIC_PATH
ENV CYPRESS_INSTALL_BINARY=$CYPRESS_INSTALL_BINARY

RUN yarn global add @vue/cli

WORKDIR /www
COPY . .


